version: "3"

services:
  nordea-queue-api:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules/

    ports:
      - "3000:3000"

    env_file:
      - .env

    environment:
      - MONGO_URL_DEV=mongodb://mongo/nordea-queue-app-dev
      - MONGO_URL_PROD=mongodb://mongo/nordea-queue-app-prod
      - NODE_ENV=production

    depends_on:
      - mongo

  mongo:
    image: "mongo"
    restart: always
    ports:
      - "27017:27017"

